name: Moodle Plugin CI

on: [push, pull_request]

jobs:
  citest:
    name: CI
    runs-on: ubuntu-18.04

    strategy:
      fail-fast: false
      matrix:
        include:
          - php: '7.4'
            moodle-branch: 'master'
            node-version: '14.15.0'
          - php: '7.3'
            moodle-branch: 'MOODLE_311_STABLE'
            node-version: '14.15.0'
          - php: '7.3'
            moodle-branch: 'MOODLE_310_STABLE'
            node-version: '14.15.0'
          - php: '7.2'
            moodle-branch: 'MOODLE_39_STABLE'
            node-version: '14.15.0'
          - php: '7.2'
            moodle-branch: 'MOODLE_38_STABLE'
            node-version: '14.15.0'
          - php: '7.2'
            moodle-branch: 'MOODLE_37_STABLE'
            node-version: '14.15.0'
          - php: '7.0'
            moodle-branch: 'MOODLE_36_STABLE'
            node-version: '8.16.1'
          - php: '7.0'
            moodle-branch: 'MOODLE_35_STABLE'
            node-version: '14.15.0'

    services:
      postgres:
        image: postgres:9.6
        env:
          POSTGRES_USER: 'postgres'
          POSTGRES_HOST_AUTH_METHOD: 'trust'
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 3

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        path: plugin

    - name: Install node
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php }}
        extensions: pgsql, zip, gd
        coverage: none

    - name: Deploy moodle-plugin-ci
      run: |
        composer create-project -n --no-dev --prefer-dist moodlehq/moodle-plugin-ci ci ^3
        echo $(cd ci/bin; pwd) >> $GITHUB_PATH
        echo $(cd ci/vendor/bin; pwd) >> $GITHUB_PATH
        # PHPUnit depends on en_AU.UTF-8 locale
        sudo locale-gen en_AU.UTF-8

    - name: Install Moodle
      run: moodle-plugin-ci install --plugin ./plugin --db-host=127.0.0.1
      env:
        DB: 'pgsql'
        MOODLE_BRANCH: ${{ matrix.moodle-branch }}

    - name: Run phplint
      if: ${{ always() }}
      run: moodle-plugin-ci phplint

    - name: Run phpcpd
      if: ${{ always() }}
      run: moodle-plugin-ci phpcpd

    - name: Run phpmd
      if: ${{ always() }}
      run: moodle-plugin-ci phpmd

    - name: Run codechecker
      if: ${{ always() }}
      run: moodle-plugin-ci codechecker

    - name: Run validate
      if: ${{ always() }}
      run: moodle-plugin-ci validate

    - name: Run savepoints
      if: ${{ always() }}
      run: moodle-plugin-ci savepoints

    - name: Run grunt
      if: ${{ always() }}
      run: moodle-plugin-ci grunt

    - name: Run phpdoc
      if: ${{ always() }}
      run: moodle-plugin-ci phpdoc

    - name: Run phpunit
      if: ${{ always() }}
      run: moodle-plugin-ci phpunit
